### ISSUE TITLE
Deduplication of efforts

### ISSUE THREAD

**Issue by fridtjof** [cryptofyre/Apple-Music-Electron#98]
While looking for an AUR package for this, I found another repository that does the same thing through the AUR: https://github.com/17hoehbr/Apple-Music-Electron

Now, it seems like both of you seem to have the same goal essentially. Maybe it makes sense to collaborate? Or are there major differences that I did not spot at first glance?

**Comment by fridtjof** [comment]
(Sister issue: https://github.com/17hoehbr/apple-music-electron/issues/24)

**Comment by cryptofyre** [comment]
I'd be interested in collaborating if possible.

**Comment by 17hoehbr** [comment]
Mine was created a few months earlier and was mostly done for my own personal use as there was nothing else around at the time. Both are based on node and are pretty similar overall, however at a glance it seems like cryptofyre's version is more polished and more actively maintained. I think collaboration would be better for all of us so what I think I'll do is review the code to see if anything from my repo can be merged in, then mark it as deprecated and push users over here. I can also update or transfer the AUR package to this repo.

**Comment by cryptofyre** [comment]
That sounds awesome! Thanks so much!

**Comment by 17hoehbr** [comment]
no problem! it doesn't make much sense to artificially split the user base since they're fundamentally the same thing and your version definitely seems more polished and feature complete. 

Let me know if there's anything in particular from my repo that you'd like me to merge. As far as I can tell the only feature exclusive to my repo is proxy support, but I'm not sure how we'd implement it without adding the entire settings dropdown.

Otherwise I also have Solus support and a streamer mode documented, but neither should require any actual code changes so I should be able to just add those to the wiki.
